### ISSUE TITLE
测试问题

### ISSUE THREAD

**Issue by kangkang189** [weijiang1994/BookManage#1]
作者你好，我发现我无法归还图书以及我的归还状态一直是None并不是未还，这个要怎么处理呀？还有催还按钮无效

**Comment by weijiang1994** [comment]
> 作者你好，我发现我无法归还图书以及我的归还状态一直是None并不是未还，这个要怎么处理呀？还有催还按钮无效

这个好像还没有实现，太久了没更新了，我有点忘记了😂

**Comment by kangkang189** [comment]
能否帮忙稍微看一下为啥无法归还吗，有急用，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月6日(星期五) 下午3:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [weijiang1994/BookManage] 测试问题 (Issue #1)





  
作者你好，我发现我无法归还图书以及我的归还状态一直是None并不是未还，这个要怎么处理呀？还有催还按钮无效
  
这个好像还没有实现，太久了没更新了，我有点忘记了😂

**Comment by weijiang1994** [comment]
> 能否帮忙稍微看一下为啥无法归还吗，有急用，谢谢！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年1月6日(星期五) 下午3:33 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [weijiang1994/BookManage] 测试问题 (Issue #1) 作者你好，我发现我无法归还图书以及我的归还状态一直是None并不是未还，这个要怎么处理呀？还有催还按钮无效 这个好像还没有实现，太久了没更新了，我有点忘记了😂 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

没时间，在上班

**Comment by kangkang189** [comment]
没事了，我改出来啦，多谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月6日(星期五) 下午5:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [weijiang1994/BookManage] 测试问题 (Issue #1)





  
能否帮忙稍微看一下为啥无法归还吗，有急用，谢谢！
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年1月6日(星期五) 下午3:33 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [weijiang1994/BookManage] 测试问题 (Issue #1) 作者你好，我发现我无法归还图书以及我的归还状态一直是None并不是未还，这个要怎么处理呀？还有催还按钮无效 这个好像还没有实现，太久了没更新了，我有点忘记了😂 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
没时间，在上班

**Comment by tianyang123** [comment]
> 没事了，我改出来啦，多谢！
> [...](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年1月6日(星期五) 下午5:32 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [weijiang1994/BookManage] 测试问题 (Issue #1) 能否帮忙稍微看一下为啥无法归还吗，有急用，谢谢！ … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年1月6日(星期五) 下午3:33 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [weijiang1994/BookManage] 测试问题 (Issue #1) 作者你好，我发现我无法归还图书以及我的归还状态一直是None并不是未还，这个要怎么处理呀？还有催还按钮无效 这个好像还没有实现，太久了没更新了，我有点忘记了😂 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 没时间，在上班 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你好请问你是怎么修改的啊我也遇到这个问题了
